version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecg_server
    ports:
      - "5000:8000" # Map port 5000 VPS ke port 8000 kontainer
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      # Map folder 'model' dari lokal ke kontainer (opsional, jika model sering update)
      # - ./backend/model:/app/model
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Kamu bisa set environment variable di sini
      - DATABASE_URL=sqlite:////app/data/ecg_data.db # Path DB di dalam kontainer
      - TZ=Asia/Jakarta
      # - MODEL_PATH=/app/model/beat_classifier_model_FINAL.keras
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --log-level info --access-logfile - --error-logfile - app:app
    restart: always # Otomatis restart jika crash, kecuali dihentikan manual
